### ISSUE TITLE
Use EnvironmentPlugin instead of DefinePlugin

### ISSUE THREAD

**Issue by pvorona** [rstacruz/webpack-tricks#10]
In case you only want to set NODE_ENV, it is possible to pass it from env vars like this:
```
new webpack.EnvironmentPlugin([
  'NODE_ENV',
]),
```
no need to use define plugin

**Comment by xavhan** [comment]
I like to use this trick for this kind of things : 
when you use npm scripts for running webpack it set "npm_lifecycle_event" to the npm script name.

$ npm run build 
```js
const ENV = process.env.npm_lifecycle_event
if(ENV === 'build'){
  // production process
}
else{
  // dev process
}
```

**Comment by rstacruz** [comment]
In Webpack 2, doing `webpack -p` now sets `NODE_ENV=production`, so I think checking for env is best done with `process.env.NODE_ENV`. I've noted this now since I started adding in Webpack 2 notes.
