### ISSUE TITLE
analyze bundle size with source map explorer

### ISSUE THREAD

**Issue by lucasavila00** [rstacruz/webpack-tricks#11]
it has a better ui and works with create-inferno-app out of the box, for instance. check it out later, guys https://www.npmjs.com/package/source-map-explorer

**Comment by rstacruz** [comment]
Thanks! I like source-map-explorer, but I feel it's not /that/ useful in actually finding out big packages. If your app depends on package A, which then depends on package B, C, D.. Z, it won't tell you that removing package A will save you a LOT of bytes. It only tells you how much A (without B...Z) is using.

With that said, it's still an amazing tool and deserves a mention.
